namespace DL.MusicStore.Persistence.EF.Migrations
{
    using DL.MusicStore.Domain;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<DL.MusicStore.Persistence.EF.MSDbContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(DL.MusicStore.Persistence.EF.MSDbContext context)
        {
            //  This method will be called after migrating to the latest version.

            var styles = new AlbumStyle[]
            {
                new AlbumStyle("Rock"),
                new AlbumStyle("Jazz"),
                new AlbumStyle("Metal"),
                new AlbumStyle("Alternative"),
                new AlbumStyle("Disco"),
                new AlbumStyle("Blues"),
                new AlbumStyle("Latin"),
                new AlbumStyle("Reggae"),
                new AlbumStyle("Pop"),
                new AlbumStyle("Classical")
            };

            var artists = new Artist[]
            {
                new Artist("Aaron Copland & London Symphony Orchestra"),
                new Artist("Aaron Goldberg"),
                new Artist("AC/DC"),
                new Artist("Accept"),
                new Artist("Adrian Leaper & Doreen de Feis"),
                new Artist("Aerosmith"),
                new Artist("Aisha Duo"),
                new Artist("Alanis Morissette"),
                new Artist("Alberto Turco & Nova Schola Gregoriana"),
                new Artist("Alice In Chains"),
                new Artist("Amy Winehouse"),
                new Artist("Anita Ward"),
                new Artist("Antônio Carlos Jobim"),
                new Artist("Apocalyptica"),
                new Artist("Audioslave"),
                new Artist("Barry Wordsworth & BBC Concert Orchestra"),
                new Artist("Berliner Philharmoniker & Hans Rosbaud"),
                new Artist("Berliner Philharmoniker & Herbert Von Karajan"),
                new Artist("Billy Cobham"),
                new Artist("Black Label Society"),
                new Artist("Black Sabbath"),
                new Artist("Boston Symphony Orchestra & Seiji Ozawa"),
                new Artist("Britten Sinfonia, Ivor Bolton & Lesley Garrett"),
                new Artist("Bruce Dickinson"),
                new Artist("Buddy Guy"),
                new Artist("Caetano Veloso"),
                new Artist("Cake"),
                new Artist("Calexico"),
                new Artist("Cássia Eller"),
                new Artist("Chic"),
                new Artist("Chicago Symphony Orchestra & Fritz Reiner"),
                new Artist("Chico Buarque"),
                new Artist("Chico Science & Nação Zumbi"),
                new Artist("Choir Of Westminster Abbey & Simon Preston"),
                new Artist("Chris Cornell"),
                new Artist("Christopher O'Riley"),
                new Artist("Cidade Negra"),
                new Artist("Cláudio Zoli"),
                new Artist("Creedence Clearwater Revival"),
                new Artist("David Coverdale"),
                new Artist("Deep Purple"),
                new Artist("Dennis Chambers"),
                new Artist("Djavan"),
                new Artist("Donna Summer"),
                new Artist("Dread Zeppelin"),
                new Artist("Ed Motta"),
                new Artist("Edo de Waart & San Francisco Symphony"),
                new Artist("Elis Regina"),
                new Artist("English Concert & Trevor Pinnock"),
                new Artist("Eric Clapton"),
                new Artist("Eugene Ormandy"),
                new Artist("Faith No More"),
                new Artist("Falamansa"),
                new Artist("Foo Fighters"),
                new Artist("Frank Zappa & Captain Beefheart"),
                new Artist("Fretwork"),
                new Artist("Funk Como Le Gusta"),
                new Artist("Gerald Moore"),
                new Artist("Gilberto Gil"),
                new Artist("Godsmack"),
                new Artist("Gonzaguinha"),
                new Artist("Göteborgs Symfoniker & Neeme Järvi"),
                new Artist("Guns N' Roses"),
                new Artist("Gustav Mahler"),
                new Artist("Incognito"),
                new Artist("Iron Maiden"),
                new Artist("James Levine"),
                new Artist("Jamiroquai"),
                new Artist("Jimi Hendrix"),
                new Artist("Joe Satriani"),
                new Artist("Jorge Ben"),
                new Artist("Jota Quest"),
                new Artist("Judas Priest"),
                new Artist("Julian Bream"),
                new Artist("Kent Nagano and Orchestre de l'Opéra de Lyon"),
                new Artist("Kiss"),
                new Artist("Led Zeppelin"),
                new Artist("Legião Urbana"),
                new Artist("Lenny Kravitz"),
                new Artist("Les Arts Florissants & William Christie"),
                new Artist("London Symphony Orchestra & Sir Charles Mackerras"),
                new Artist("Luciana Souza/Romero Lubambo"),
                new Artist("Lulu Santos"),
                new Artist("Marcos Valle"),
                new Artist("Marillion"),
                new Artist("Marisa Monte"),
                new Artist("Martin Roscoe"),
                new Artist("Maurizio Pollini"),
                new Artist("Mela Tenenbaum, Pro Musica Prague & Richard Kapp"),
                new Artist("Men At Work"),
                new Artist("Metallica"),
                new Artist("Michael Tilson Thomas & San Francisco Symphony"),
                new Artist("Miles Davis"),
                new Artist("Milton Nascimento"),
                new Artist("Mötley Crüe"),
                new Artist("Motörhead"),
                new Artist("Nash Ensemble"),
                new Artist("Nicolaus Esterhazy Sinfonia"),
                new Artist("Nirvana"),
                new Artist("O Terço"),
                new Artist("Olodum"),
                new Artist("Orchestra of The Age of Enlightenment"),
                new Artist("Os Paralamas Do Sucesso"),
                new Artist("Ozzy Osbourne"),
                new Artist("Page & Plant"),
                new Artist("Paul D'Ianno"),
                new Artist("Pearl Jam"),
                new Artist("Pink Floyd"),
                new Artist("Queen"),
                new Artist("R.E.M."),
                new Artist("Raul Seixas"),
                new Artist("Red Hot Chili Peppers"),
                new Artist("Roger Norrington, London Classical Players"),
                new Artist("Royal Philharmonic Orchestra & Sir Thomas Beecham"),
                new Artist("Rush"),
                new Artist("Santana"),
                new Artist("Scholars Baroque Ensemble"),
                new Artist("Scorpions"),
                new Artist("Sergei Prokofiev & Yuri Temirkanov"),
                new Artist("Sir Georg Solti & Wiener Philharmoniker"),
                new Artist("Skank"),
                new Artist("Soundgarden"),
                new Artist("Spyro Gyra"),
                new Artist("Stevie Ray Vaughan & Double Trouble"),
                new Artist("Stone Temple Pilots"),
                new Artist("System Of A Down"),
                new Artist("Temple of the Dog"),
                new Artist("Terry Bozzio, Tony Levin & Steve Stevens"),
                new Artist("The 12 Cellists of The Berlin Philharmonic"),
                new Artist("The Black Crowes"),
                new Artist("The Cult"),
                new Artist("The Doors"),
                new Artist("The King's Singers"),
                new Artist("The Police"),
                new Artist("The Posies"),
                new Artist("The Rolling Stones"),
                new Artist("The Who"),
                new Artist("Tim Maia"),
                new Artist("Ton Koopman"),
                new Artist("U2"),
                new Artist("UB40"),
                new Artist("Van Halen"),
                new Artist("Various Artists"),
                new Artist("Velvet Revolver"),
                new Artist("Vinícius De Moraes"),
                new Artist("Wilhelm Kempff"),
                new Artist("Yehudi Menuhin"),
                new Artist("Yo-Yo Ma"),
                new Artist("Zeca Pagodinho")
            };

            var albums = new Album[]
            {
                new Album("The Best Of Men At Work", 34.98, new DateTime(1996,4,2), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Men At Work")),
                new Album("A Copland Celebration, Vol. I", 3.81, new DateTime(2000,11,7),  styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Aaron Copland & London Symphony Orchestra")),
                new Album("Worlds", 19.99, new DateTime(2014,8,12), styles.Single(s => s.Name == "Jazz"), artists.Single(a => a.Name == "Aaron Goldberg")),
                new Album("For Those About To Rock We Salute You", 8.69, new DateTime(2003,4,29), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "AC/DC")),
                new Album("Let There Be Rock", 8.69, new DateTime(2003,4,29), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "AC/DC")),
                new Album("Balls to the Wall", 6.99, new DateTime(2001,8,28), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Accept")),
                new Album("Restless and Wild", 4.99, new DateTime(2008,1,14), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Accept")),
                new Album("Górecki: Symphony No. 3", 13.92, new DateTime(1992,5,5), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Adrian Leaper & Doreen de Feis")),
                new Album("Big Ones", 9.24, new DateTime(1994,11,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Aerosmith")),
                new Album("Quiet Songs", 10.58, new DateTime(2006,4,11), styles.Single(s => s.Name == "Jazz"), artists.Single(a => a.Name == "Aisha Duo")),
                new Album("Jagged Little Pill", 20.62, new DateTime(2012,12,4), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Alanis Morissette")),
                new Album("Facelift", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Alice In Chains")),
                new Album("Frank", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Pop"), artists.Single(a => a.Name == "Amy Winehouse")),
                new Album("Ring My Bell", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Disco"), artists.Single(a => a.Name == "Anita Ward")),
                new Album("Chill: Brazil (Disc 2)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Antônio Carlos Jobim")),
                new Album("Warner 25 Anos", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Jazz"), artists.Single(a => a.Name == "Antônio Carlos Jobim")),
                new Album("Plays Metallica By Four Cellos", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Apocalyptica")),
                new Album("Revelations", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Alternative"), artists.Single(a => a.Name == "Audioslave")),
                new Album("Audioslave", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Audioslave")),
                new Album("The Last Night of the Proms", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Barry Wordsworth & BBC Concert Orchestra")),
                new Album("Sibelius: Finlandia", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Berliner Philharmoniker & Hans Rosbaud")),
                new Album("Mozart: Symphonies Nos. 40 & 41", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Berliner Philharmoniker & Herbert Von Karajan")),
                new Album("The Best Of Billy Cobham", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Jazz"), artists.Single(a => a.Name == "Billy Cobham")),
                new Album("Alcohol Fueled Brewtality Live! [Disc 1]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Black Label Society")),
                new Album("Alcohol Fueled Brewtality Live! [Disc 2]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Black Label Society")),
                new Album("Black Sabbath Vol. 4 (Remaster)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Black Sabbath")),
                new Album("Black Sabbath", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Black Sabbath")),
                new Album("Carmina Burana", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Boston Symphony Orchestra & Seiji Ozawa")),
                new Album("A Soprano Inspired", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Britten Sinfonia, Ivor Bolton & Lesley Garrett")),
                new Album("Chemical Wedding", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Bruce Dickinson")),
                new Album("Prenda Minha", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Caetano Veloso")),
                new Album("Sozinho Remix Ao Vivo", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Caetano Veloso")),
                new Album("Cake: B-Sides and Rarities", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Alternative"), artists.Single(a => a.Name == "Cake")),
                new Album("Carried to Dust (Bonus Track Version)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Alternative"), artists.Single(a => a.Name == "Calexico")),
                new Album("Cássia Eller - Sem Limite [Disc 1]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Cássia Eller")),
                new Album("Le Freak", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Disco"), artists.Single(a => a.Name == "Chic")),
                new Album("Scheherazade", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Chicago Symphony Orchestra & Fritz Reiner")),
                new Album("Minha Historia", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Chico Buarque")),
                new Album("Afrociberdelia", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Chico Science & Nação Zumbi")),
                new Album("Da Lama Ao Caos", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Chico Science & Nação Zumbi")),
                new Album("Carry On", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Alternative"), artists.Single(a => a.Name == "Chris Cornell")),
                new Album("SCRIABIN: Vers la flamme", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Christopher O'Riley")),
                new Album("Acústico MTV [Live]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Reggae"), artists.Single(a => a.Name == "Cidade Negra")),
                new Album("Cidade Negra - Hits", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Reggae"), artists.Single(a => a.Name == "Cidade Negra")),
                new Album("Na Pista", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Cláudio Zoli")),
                new Album("Chronicle, Vol. 1", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Creedence Clearwater Revival")),
                new Album("Chronicle, Vol. 2", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Creedence Clearwater Revival")),
                new Album("Into The Light", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "David Coverdale")),
                new Album("Come Taste The Band", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Deep Purple")),
                new Album("Deep Purple In Rock", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Deep Purple")),
                new Album("Fireball", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Deep Purple")),
                new Album("Machine Head", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Deep Purple")),
                new Album("MK III The Final Concerts [Disc 1]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Deep Purple")),
                new Album("Purpendicular", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Deep Purple")),
                new Album("Slaves And Masters", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Deep Purple")),
                new Album("Stormbringer", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Deep Purple")),
                new Album("The Battle Rages On", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Deep Purple")),
                new Album("The Final Concerts (Disc 2)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Deep Purple")),
                new Album("Outbreak", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Jazz"), artists.Single(a => a.Name == "Dennis Chambers")),
                new Album("Djavan Ao Vivo - Vol. 02", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Djavan")),
                new Album("Djavan Ao Vivo - Vol. 1", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Djavan")),
                new Album("MacArthur Park Suite", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Disco"), artists.Single(a => a.Name == "Donna Summer")),
                new Album("Un-Led-Ed", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Dread Zeppelin")),
                new Album("The Best of Ed Motta", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Ed Motta")),
                new Album("Adams, John: The Chairman Dances", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Edo de Waart & San Francisco Symphony")),
                new Album("Elis Regina-Minha História", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Elis Regina")),
                new Album("Pachelbel: Canon & Gigue", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "English Concert & Trevor Pinnock")),
                new Album("Unplugged", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Eric Clapton")),
                new Album("The Cream Of Clapton", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Blues"), artists.Single(a => a.Name == "Eric Clapton")),
                new Album("Unplugged", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Blues"), artists.Single(a => a.Name == "Eric Clapton")),
                new Album("Respighi:Pines of Rome", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Eugene Ormandy")),
                new Album("Strauss: Waltzes", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Eugene Ormandy")),
                new Album("King For A Day Fool For A Lifetime", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Faith No More")),
                new Album("Deixa Entrar", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Falamansa")),
                new Album("In Your Honor [Disc 1]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Foo Fighters")),
                new Album("In Your Honor [Disc 2]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Foo Fighters")),
                new Album("The Colour And The Shape", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Foo Fighters")),
                new Album("Bongo Fury", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Frank Zappa & Captain Beefheart")),
                new Album("Roda De Funk", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Funk Como Le Gusta")),
                new Album("Quanta Gente Veio Ver (Live)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Gilberto Gil")),
                new Album("Quanta Gente Veio ver--Bônus De Carnaval", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Jazz"), artists.Single(a => a.Name == "Gilberto Gil")),
                new Album("Faceless", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Godsmack")),
                new Album("Meus Momentos", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Gonzaguinha")),
                new Album("Nielsen: The Six Symphonies", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Göteborgs Symfoniker & Neeme Järvi")),
                new Album("Appetite for Destruction", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Guns N' Roses")),
                new Album("Use Your Illusion I", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Guns N' Roses")),
                new Album("Use Your Illusion II", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Guns N' Roses")),
                new Album("Blue Moods", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Jazz"), artists.Single(a => a.Name == "Incognito")),
                new Album("A Matter of Life and Death", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Brave New World", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Fear Of The Dark", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Live At Donington 1992 (Disc 1)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Live At Donington 1992 (Disc 2)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Rock In Rio [CD2]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("The Number of The Beast", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("The X Factor", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Virtual XI", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("A Real Dead One", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("A Real Live One", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Live After Death", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("No Prayer For The Dying", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Piece Of Mind", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Powerslave", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Rock In Rio [CD1]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Rock In Rio [CD2]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Seventh Son of a Seventh Son", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Somewhere in Time", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("The Number of The Beast", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Iron Maiden", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Blues"), artists.Single(a => a.Name == "Iron Maiden")),
                new Album("Mascagni: Cavalleria Rusticana", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "James Levine")),
                new Album("Emergency On Planet Earth", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Jamiroquai")),
                new Album("Are You Experienced?", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Jimi Hendrix")),
                new Album("Surfing with the Alien (Remastered)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Joe Satriani")),
                new Album("Jorge Ben Jor 25 Anos", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Jorge Ben")),
                new Album("Jota Quest-1995", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Jota Quest")),
                new Album("Living After Midnight", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Judas Priest")),
                new Album("Weill: The Seven Deadly Sins", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Kent Nagano and Orchestre de l'Opéra de Lyon")),
                new Album("Greatest Kiss", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Kiss")),
                new Album("Unplugged [Live]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Kiss")),
                new Album("BBC Sessions [Disc 1] [Live]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("BBC Sessions [Disc 2] [Live]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("Coda", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("Houses Of The Holy", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("In Through The Out Door", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("IV", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("Led Zeppelin I", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("Led Zeppelin II", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("Led Zeppelin III", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("Physical Graffiti [Disc 1]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("Physical Graffiti [Disc 2]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("Presence", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("The Song Remains The Same (Disc 1)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("The Song Remains The Same (Disc 2)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Led Zeppelin")),
                new Album("Mais Do Mesmo", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Legião Urbana")),
                new Album("Greatest Hits", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Reggae"), artists.Single(a => a.Name == "Lenny Kravitz")),
                new Album("Greatest Hits", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Lenny Kravitz")),
                new Album("Greatest Hits", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Lenny Kravitz")),
                new Album("Tchaikovsky: The Nutcracker", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "London Symphony Orchestra & Sir Charles Mackerras")),
                new Album("Duos II", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Luciana Souza/Romero Lubambo")),
                new Album("Chill: Brazil (Disc 1)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Marcos Valle")),
                new Album("Misplaced Childhood", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Marillion")),
                new Album("Barulhinho Bom", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Marisa Monte")),
                new Album("Szymanowski: Piano Works, Vol. 1", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Martin Roscoe")),
                new Album("...And Justice For All", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Metallica")),
                new Album("Black Album", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Metallica")),
                new Album("Garage Inc. (Disc 1)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Metallica")),
                new Album("Garage Inc. (Disc 2)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Metallica")),
                new Album("Load", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Metallica")),
                new Album("Master Of Puppets", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Metallica")),
                new Album("ReLoad", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Metallica")),
                new Album("Ride The Lightning", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Metallica")),
                new Album("St. Anger", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Metallica")),
                new Album("Berlioz: Symphonie Fantastique", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony")),
                new Album("Prokofiev: Romeo & Juliet", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony")),
                new Album("Miles Ahead", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Jazz"), artists.Single(a => a.Name == "Miles Davis")),
                new Album("The Essential Miles Davis [Disc 1]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Jazz"), artists.Single(a => a.Name == "Miles Davis")),
                new Album("The Essential Miles Davis [Disc 2]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Jazz"), artists.Single(a => a.Name == "Miles Davis")),
                new Album("Milton Nascimento Ao Vivo", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Milton Nascimento")),
                new Album("Minas", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Milton Nascimento")),
                new Album("Motley Crue Greatest Hits", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Mötley Crüe")),
                new Album("Ace Of Spades", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Motörhead")),
                new Album("Mozart: Chamber Music", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Nash Ensemble")),
                new Album("The Best of Beethoven", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Nicolaus Esterhazy Sinfonia")),
                new Album("Nevermind", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Nirvana")),
                new Album("Compositores", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "O Terço")),
                new Album("Olodum", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Olodum")),
                new Album("Bach: The Brandenburg Concertos", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Orchestra of The Age of Enlightenment")),
                new Album("Acústico MTV", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Os Paralamas Do Sucesso")),
                new Album("Arquivo II", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Os Paralamas Do Sucesso")),
                new Album("Arquivo Os Paralamas Do Sucesso", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Os Paralamas Do Sucesso")),
                new Album("Tribute", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "Ozzy Osbourne")),
                new Album("Bark at the Moon (Remastered)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Ozzy Osbourne")),
                new Album("Blizzard of Ozz", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Ozzy Osbourne")),
                new Album("Diary of a Madman (Remastered)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Ozzy Osbourne")),
                new Album("No More Tears (Remastered)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Ozzy Osbourne")),
                new Album("Speak of the Devil", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Ozzy Osbourne")),
                new Album("Walking Into Clarksdale", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Page & Plant")),
                new Album("The Beast Live", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Paul D'Ianno")),
                new Album("Live On Two Legs [Live]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Pearl Jam")),
                new Album("Riot Act", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Pearl Jam")),
                new Album("Ten", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Pearl Jam")),
                new Album("Vs.", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Pearl Jam")),
                new Album("Dark Side Of The Moon", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Pink Floyd")),
                new Album("Greatest Hits I", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Queen")),
                new Album("Greatest Hits II", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Queen")),
                new Album("News Of The World", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Queen")),
                new Album("New Adventures In Hi-Fi", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "R.E.M.")),
                new Album("Raul Seixas", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Raul Seixas")),
                new Album("By The Way", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Red Hot Chili Peppers")),
                new Album("Californication", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Red Hot Chili Peppers")),
                new Album("Purcell: The Fairy Queen", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Roger Norrington, London Classical Players")),
                new Album("Haydn: Symphonies 99 - 104", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Royal Philharmonic Orchestra & Sir Thomas Beecham")),
                new Album("Retrospective I (1974-1980)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Rush")),
                new Album("Santana - As Years Go By", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Santana")),
                new Album("Santana Live", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Santana")),
                new Album("Supernatural", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Santana")),
                new Album("Handel: The Messiah (Highlights)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Scholars Baroque Ensemble")),
                new Album("Prokofiev: Symphony No.1", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Sergei Prokofiev & Yuri Temirkanov")),
                new Album("Wagner: Favourite Overtures", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Sir Georg Solti & Wiener Philharmoniker")),
                new Album("Maquinarama", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Skank")),
                new Album("O Samba Poconé", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Skank")),
                new Album("A-Sides", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Soundgarden")),
                new Album("Heart of the Night", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Jazz"), artists.Single(a => a.Name == "Spyro Gyra")),
                new Album("Morning Dance", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Jazz"), artists.Single(a => a.Name == "Spyro Gyra")),
                new Album("In Step", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Blues"), artists.Single(a => a.Name == "Stevie Ray Vaughan & Double Trouble")),
                new Album("Core", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Stone Temple Pilots")),
                new Album("Mezmerize", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Metal"), artists.Single(a => a.Name == "System Of A Down")),
                new Album("Temple of the Dog", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Alternative"), artists.Single(a => a.Name == "Temple of the Dog")),
                new Album("[1997] Black Light Syndrome", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Terry Bozzio, Tony Levin & Steve Stevens")),
                new Album("South American Getaway", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "The 12 Cellists of The Berlin Philharmonic")),
                new Album("Live [Disc 1]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Blues"), artists.Single(a => a.Name == "The Black Crowes")),
                new Album("Live [Disc 2]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Blues"), artists.Single(a => a.Name == "The Black Crowes")),
                new Album("Beyond Good And Evil", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "The Cult")),
                new Album("The Doors", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "The Doors")),
                new Album("English Renaissance", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "The King's Singers")),
                new Album("The Police Greatest Hits", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "The Police")),
                new Album("Every Kind of Light", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "The Posies")),
                new Album("Hot Rocks, 1964-1971 (Disc 1)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "The Rolling Stones")),
                new Album("No Security", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "The Rolling Stones")),
                new Album("Voodoo Lounge", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "The Rolling Stones")),
                new Album("My Generation - The Very Best Of The Who", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "The Who")),
                new Album("Serie Sem Limite (Disc 1)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Tim Maia")),
                new Album("Serie Sem Limite (Disc 2)", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Tim Maia")),
                new Album("Bach: Toccata & Fugue in D Minor", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Ton Koopman")),
                new Album("Achtung Baby", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "U2")),
                new Album("B-Sides 1980-1990", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "U2")),
                new Album("How To Dismantle An Atomic Bomb", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "U2")),
                new Album("Pop", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "U2")),
                new Album("Rattle And Hum", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "U2")),
                new Album("The Best Of 1980-1990", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "U2")),
                new Album("War", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "U2")),
                new Album("Zooropa", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "U2")),
                new Album("UB40 The Best Of - Volume Two [UK]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Reggae"), artists.Single(a => a.Name == "UB40")),
                new Album("Diver Down", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Van Halen")),
                new Album("The Best Of Van Halen, Vol. I", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Van Halen")),
                new Album("Van Halen III", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Van Halen")),
                new Album("Van Halen", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Van Halen")),
                new Album("Axé Bahia 2001", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Pop"), artists.Single(a => a.Name == "Various Artists")),
                new Album("Sambas De Enredo 2001", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Various Artists")),
                new Album("Vozes do MPB", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Various Artists")),
                new Album("Contraband", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Rock"), artists.Single(a => a.Name == "Velvet Revolver")),
                new Album("Vinicius De Moraes", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Vinícius De Moraes")),
                new Album("Bach: Goldberg Variations", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Wilhelm Kempff")),
                new Album("Bartok: Violin & Viola Concertos", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Yehudi Menuhin")),
                new Album("Bach: The Cello Suites", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Classical"), artists.Single(a => a.Name == "Yo-Yo Ma")),
                new Album("Ao Vivo [IMPORT]", 6.99, new DateTime(2001,1,1), styles.Single(s => s.Name == "Latin"), artists.Single(a => a.Name == "Zeca Pagodinho"))
            };

            context.Set<AlbumStyle>().AddOrUpdate(s => s.Name, styles);
            context.Set<Artist>().AddOrUpdate(ar => ar.Name, artists);
            context.Set<Album>().AddOrUpdate(a => a.Title, albums);
        }
    }
}
